// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_ApplicationModel_Preview_H
#define WINRT_Windows_ApplicationModel_Preview_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/Windows.ApplicationModel.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.ApplicationModel.Preview.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppInfoPreview<D>::DisplayName() const
    {
        void* value{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>::get_DisplayName, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppInfoPreview<D>::Publisher() const
    {
        void* value{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>::get_Publisher, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppInfoPreview<D>::IsEnabled() const
    {
        bool value{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>::get_IsEnabled, &value);
        return value;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppInfoPreview<D>::Impact() const
    {
        winrt::Windows::ApplicationModel::Preview::StartupAppImpactPreview value{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>::get_Impact, reinterpret_cast<std::int32_t*>(&value));
        return value;
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppInfoPreview<D>::ExecutablePath() const
    {
        void* value{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>::get_ExecutablePath, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppsManagerPreview<D>::GetStartupAppInfos() const
    {
        void* result{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview>::GetStartupAppInfos, &result);
        return winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::ApplicationModel::Preview::StartupAppInfoPreview>{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_ApplicationModel_Preview_IStartupAppsManagerPreviewStatics<D>::GetDefault() const
    {
        void* result{};
        consume_general<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreviewStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreviewStatics>::GetDefault, &result);
        return winrt::Windows::ApplicationModel::Preview::StartupAppsManagerPreview{ result, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview> : produce_base<D, winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview>
    {
        std::int32_t __stdcall get_DisplayName(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().DisplayName());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Publisher(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().Publisher());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_IsEnabled(bool* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<bool>(this->shim().IsEnabled());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_Impact(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::ApplicationModel::Preview::StartupAppImpactPreview>(this->shim().Impact());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ExecutablePath(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().ExecutablePath());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview> : produce_base<D, winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview>
    {
        std::int32_t __stdcall GetStartupAppInfos(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::ApplicationModel::Preview::StartupAppInfoPreview>>(this->shim().GetStartupAppInfos());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreviewStatics> : produce_base<D, winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreviewStatics>
    {
        std::int32_t __stdcall GetDefault(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::ApplicationModel::Preview::StartupAppsManagerPreview>(this->shim().GetDefault());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::ApplicationModel::Preview
{
    inline auto StartupAppsManagerPreview::GetDefault()
    {
        return impl::call_factory_cast<winrt::Windows::ApplicationModel::Preview::StartupAppsManagerPreview(*)(IStartupAppsManagerPreviewStatics const&), StartupAppsManagerPreview, IStartupAppsManagerPreviewStatics>([](IStartupAppsManagerPreviewStatics const& f) { return f.GetDefault(); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::ApplicationModel::Preview::IStartupAppInfoPreview> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreview> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Preview::IStartupAppsManagerPreviewStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Preview::StartupAppInfoPreview> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::ApplicationModel::Preview::StartupAppsManagerPreview> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
