// WARNING: Please don't edit this file. It was generated by C++/WinRT v3.0.260520.1

#pragma once
#ifndef WINRT_Windows_System_Power_Thermal_H
#define WINRT_Windows_System_Power_Thermal_H
#ifndef WINRT_IMPORT_MODULE

#ifndef WINRT_IMPL_BUILD_MODULE
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "3.0.260520.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "3.0.260520.1"
#include "winrt/Windows.System.Power.h"
#include "winrt/impl/Windows.Foundation.2.h"
#include "winrt/impl/Windows.Foundation.Collections.2.h"
#include "winrt/impl/Windows.System.Power.Thermal.2.h"
#endif // WINRT_IMPL_BUILD_MODULE
WINRT_EXPORT namespace winrt::impl
{
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelConfiguration<D>::Id() const
    {
        winrt::Windows::System::Power::Thermal::PowerThermalChannelId value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration>::get_Id, put_abi(value));
        return value;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelConfiguration<D>::ConfigurationString() const
    {
        void* value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration>::get_ConfigurationString, &value);
        return hstring{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelConfiguration<D>::GetConfigurationNumericParameters() const
    {
        std::uint32_t result_impl_size{};
        std::int32_t* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration>::GetConfigurationNumericParameters, &result_impl_size, &result);
        return com_array<std::int32_t>{ result, result_impl_size, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::GetChannelIds() const
    {
        std::uint32_t result_impl_size{};
        struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::GetChannelIds, &result_impl_size, &result);
        return com_array<winrt::Windows::System::Power::Thermal::PowerThermalChannelId>{ result, result_impl_size, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::GetChannelConfigurations() const
    {
        void* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::GetChannelConfigurations, &result);
        return winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::System::Power::Thermal::PowerThermalChannelId, winrt::Windows::System::Power::Thermal::PowerThermalChannelConfiguration>{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::Start() const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::Start);
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::Stop() const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::Stop);
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::ChannelDataReceived(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::System::Power::Thermal::PowerThermalChannelDataReceivedEventArgs> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::add_ChannelDataReceived, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::ChannelDataReceived(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::System::Power::Thermal::PowerThermalChannelDataReceivedEventArgs> const& handler) const
    {
        return impl::make_event_revoker<D, ChannelDataReceived_revoker>(this, ChannelDataReceived(handler));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::ChannelDataReceived(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::remove_ChannelDataReceived, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::BackEndStatus() const
    {
        winrt::Windows::System::Power::Thermal::PowerThermalBackEndStatus value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::get_BackEndStatus, reinterpret_cast<std::int32_t*>(&value));
        return value;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::BackEndStatusChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::add_BackEndStatusChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::BackEndStatusChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, BackEndStatusChanged_revoker>(this, BackEndStatusChanged(handler));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumer<D>::BackEndStatusChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>::remove_BackEndStatusChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataConsumerFactory<D>::CreateInstance(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds) const
    {
        void* value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumerFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumerFactory>::CreateInstance, channelIds.size(), get_abi(channelIds), &value);
        return winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::GetChannelIds() const
    {
        std::uint32_t result_impl_size{};
        struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::GetChannelIds, &result_impl_size, &result);
        return com_array<winrt::Windows::System::Power::Thermal::PowerThermalChannelId>{ result, result_impl_size, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::GetChannelConfigurations() const
    {
        void* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::GetChannelConfigurations, &result);
        return winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::System::Power::Thermal::PowerThermalChannelId, winrt::Windows::System::Power::Thermal::PowerThermalChannelConfiguration>{ result, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::DisableChannel(winrt::Windows::System::Power::Thermal::PowerThermalChannelId const& channelId) const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::DisableChannel, impl::bind_in(channelId));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::Start() const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::Start);
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::Stop() const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::Stop);
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::PublishInputChannelData(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelData const> data) const
    {
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::PublishInputChannelData, data.size(), get_abi(data));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::BackEndStatus() const
    {
        winrt::Windows::System::Power::Thermal::PowerThermalBackEndStatus value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::get_BackEndStatus, reinterpret_cast<std::int32_t*>(&value));
        return value;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::BackEndStatusChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        winrt::event_token token{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::add_BackEndStatusChanged, *(void**)(&handler), put_abi(token));
        return token;
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::BackEndStatusChanged(auto_revoke_t, winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer, winrt::Windows::Foundation::IInspectable> const& handler) const
    {
        return impl::make_event_revoker<D, BackEndStatusChanged_revoker>(this, BackEndStatusChanged(handler));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducer<D>::BackEndStatusChanged(winrt::event_token const& token) const noexcept
    {
        consume_noexcept_remove_overload<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>::remove_BackEndStatusChanged, impl::bind_in(token));
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataProducerFactory<D>::CreateInstance(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds) const
    {
        void* value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducerFactory, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducerFactory>::CreateInstance, channelIds.size(), get_abi(channelIds), &value);
        return winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDataReceivedEventArgs<D>::GetData() const
    {
        std::uint32_t result_impl_size{};
        struct struct_Windows_System_Power_Thermal_PowerThermalChannelData* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataReceivedEventArgs, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataReceivedEventArgs>::GetData, &result_impl_size, &result);
        return com_array<winrt::Windows::System::Power::Thermal::PowerThermalChannelData>{ result, result_impl_size, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDiagnosticsStatics<D>::Current() const
    {
        void* value{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics>::get_Current, &value);
        return winrt::Windows::System::Power::Thermal::PowerThermalChannelDiagnostics{ value, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelDiagnosticsStatics<D>::GetDataForChannels(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds) const
    {
        std::uint32_t result_impl_size{};
        struct struct_Windows_System_Power_Thermal_PowerThermalChannelData* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics>::GetDataForChannels, channelIds.size(), get_abi(channelIds), &result_impl_size, &result);
        return com_array<winrt::Windows::System::Power::Thermal::PowerThermalChannelData>{ result, result_impl_size, take_ownership_from_abi };
    }
    template <typename D> auto consume_Windows_System_Power_Thermal_IPowerThermalChannelFinderStatics<D>::FindChannels(winrt::guid const& channelInterfaceType) const
    {
        std::uint32_t result_impl_size{};
        struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* result{};
        consume_general<winrt::Windows::System::Power::Thermal::IPowerThermalChannelFinderStatics, D>(static_cast<D const*>(this), &abi_t<winrt::Windows::System::Power::Thermal::IPowerThermalChannelFinderStatics>::FindChannels, impl::bind_in(channelInterfaceType), &result_impl_size, &result);
        return com_array<winrt::Windows::System::Power::Thermal::PowerThermalChannelId>{ result, result_impl_size, take_ownership_from_abi };
    }
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration>
    {
        std::int32_t __stdcall get_Id(struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* value) noexcept final try
        {
            zero_abi<winrt::Windows::System::Power::Thermal::PowerThermalChannelId>(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalChannelId>(this->shim().Id());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_ConfigurationString(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<hstring>(this->shim().ConfigurationString());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetConfigurationNumericParameters(std::uint32_t* __resultSize, std::int32_t** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetConfigurationNumericParameters());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer>
    {
        std::int32_t __stdcall GetChannelIds(std::uint32_t* __resultSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetChannelIds());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetChannelConfigurations(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::System::Power::Thermal::PowerThermalChannelId, winrt::Windows::System::Power::Thermal::PowerThermalChannelConfiguration>>(this->shim().GetChannelConfigurations());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Start() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Start();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Stop() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Stop();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_ChannelDataReceived(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().ChannelDataReceived(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::System::Power::Thermal::PowerThermalChannelDataReceivedEventArgs> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_ChannelDataReceived(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().ChannelDataReceived(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
        std::int32_t __stdcall get_BackEndStatus(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalBackEndStatus>(this->shim().BackEndStatus());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_BackEndStatusChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().BackEndStatusChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_BackEndStatusChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().BackEndStatusChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumerFactory> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumerFactory>
    {
        std::int32_t __stdcall CreateInstance(std::uint32_t __channelIdsSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* channelIds, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer>(this->shim().CreateInstance(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const>(reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds), reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds) + __channelIdsSize)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer>
    {
        std::int32_t __stdcall GetChannelIds(std::uint32_t* __resultSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetChannelIds());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetChannelConfigurations(void** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            *result = detach_from<winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::System::Power::Thermal::PowerThermalChannelId, winrt::Windows::System::Power::Thermal::PowerThermalChannelConfiguration>>(this->shim().GetChannelConfigurations());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall DisableChannel(struct struct_Windows_System_Power_Thermal_PowerThermalChannelId channelId) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().DisableChannel(*reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const*>(&channelId));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Start() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Start();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall Stop() noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().Stop();
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall PublishInputChannelData(std::uint32_t __dataSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelData* data) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().PublishInputChannelData(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelData const>(reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelData const *>(data), reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelData const *>(data) + __dataSize));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall get_BackEndStatus(std::int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalBackEndStatus>(this->shim().BackEndStatus());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall add_BackEndStatusChanged(void* handler, winrt::event_token* token) noexcept final try
        {
            zero_abi<winrt::event_token>(token);
            typename D::abi_guard guard(this->shim());
            *token = detach_from<winrt::event_token>(this->shim().BackEndStatusChanged(*reinterpret_cast<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer, winrt::Windows::Foundation::IInspectable> const*>(&handler)));
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall remove_BackEndStatusChanged(winrt::event_token token) noexcept final
        {
            typename D::abi_guard guard(this->shim());
            this->shim().BackEndStatusChanged(*reinterpret_cast<winrt::event_token const*>(&token));
            return 0;
        }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducerFactory> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducerFactory>
    {
        std::int32_t __stdcall CreateInstance(std::uint32_t __channelIdsSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* channelIds, void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer>(this->shim().CreateInstance(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const>(reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds), reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds) + __channelIdsSize)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataReceivedEventArgs> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataReceivedEventArgs>
    {
        std::int32_t __stdcall GetData(std::uint32_t* __resultSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelData** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetData());
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnostics> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnostics>
    {
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics>
    {
        std::int32_t __stdcall get_Current(void** value) noexcept final try
        {
            clear_abi(value);
            typename D::abi_guard guard(this->shim());
            *value = detach_from<winrt::Windows::System::Power::Thermal::PowerThermalChannelDiagnostics>(this->shim().Current());
            return 0;
        }
        catch (...) { return to_hresult(); }
        std::int32_t __stdcall GetDataForChannels(std::uint32_t __channelIdsSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId* channelIds, std::uint32_t* __resultSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelData** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().GetDataForChannels(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const>(reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds), reinterpret_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const *>(channelIds) + __channelIdsSize)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
#ifndef WINRT_LEAN_AND_MEAN
    template <typename D>
    struct produce<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelFinderStatics> : produce_base<D, winrt::Windows::System::Power::Thermal::IPowerThermalChannelFinderStatics>
    {
        std::int32_t __stdcall FindChannels(winrt::guid channelInterfaceType, std::uint32_t* __resultSize, struct struct_Windows_System_Power_Thermal_PowerThermalChannelId** result) noexcept final try
        {
            clear_abi(result);
            typename D::abi_guard guard(this->shim());
            std::tie(*__resultSize, *result) = detach_abi(this->shim().FindChannels(*reinterpret_cast<winrt::guid const*>(&channelInterfaceType)));
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
#endif // WINRT_LEAN_AND_MEAN
}
WINRT_EXPORT namespace winrt::Windows::System::Power::Thermal
{
    inline PowerThermalChannelDataConsumer::PowerThermalChannelDataConsumer(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds) :
        PowerThermalChannelDataConsumer(impl::call_factory<PowerThermalChannelDataConsumer, IPowerThermalChannelDataConsumerFactory>([&](IPowerThermalChannelDataConsumerFactory const& f) { return f.CreateInstance(channelIds); }))
    {
    }
    inline PowerThermalChannelDataProducer::PowerThermalChannelDataProducer(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds) :
        PowerThermalChannelDataProducer(impl::call_factory<PowerThermalChannelDataProducer, IPowerThermalChannelDataProducerFactory>([&](IPowerThermalChannelDataProducerFactory const& f) { return f.CreateInstance(channelIds); }))
    {
    }
    inline auto PowerThermalChannelDiagnostics::Current()
    {
        return impl::call_factory_cast<winrt::Windows::System::Power::Thermal::PowerThermalChannelDiagnostics(*)(IPowerThermalChannelDiagnosticsStatics const&), PowerThermalChannelDiagnostics, IPowerThermalChannelDiagnosticsStatics>([](IPowerThermalChannelDiagnosticsStatics const& f) { return f.Current(); });
    }
    inline auto PowerThermalChannelDiagnostics::GetDataForChannels(array_view<winrt::Windows::System::Power::Thermal::PowerThermalChannelId const> channelIds)
    {
        return impl::call_factory<PowerThermalChannelDiagnostics, IPowerThermalChannelDiagnosticsStatics>([&](IPowerThermalChannelDiagnosticsStatics const& f) { return f.GetDataForChannels(channelIds); });
    }
    inline auto PowerThermalChannelFinder::FindChannels(winrt::guid const& channelInterfaceType)
    {
        return impl::call_factory<PowerThermalChannelFinder, IPowerThermalChannelFinderStatics>([&](IPowerThermalChannelFinderStatics const& f) { return f.FindChannels(channelInterfaceType); });
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelConfiguration> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumer> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataConsumerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducer> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataProducerFactory> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDataReceivedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnostics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelDiagnosticsStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::IPowerThermalChannelFinderStatics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelConfiguration> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataConsumer> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataProducer> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelDataReceivedEventArgs> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelDiagnostics> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Windows::System::Power::Thermal::PowerThermalChannelFinder> : winrt::impl::hash_base {};
#endif // WINRT_LEAN_AND_MEAN
#ifdef __cpp_lib_format
#endif // __cpp_lib_format
}
#endif
#endif // WINRT_IMPORT_MODULE
